ansible_host_key_checking: False

vyos_iso_url: ""
vyos_iso_local: "{{ iso_local | default('/tmp/vyos.iso') }}"
vyos_key_url: https://downloads.vyos.io/vyos-release.gpg
vyos_key_local: /tmp/vyos-release.gpg

vyos_cd_root: /mnt/cdrom
vyos_cd_squash_root: /mnt/cdsquash
vyos_squashfs_image: "{{ vyos_cd_root }}/live/filesystem.squashfs"
vyos_write_root: /mnt/wroot
vyos_read_root: /mnt/squashfs
vyos_install_root: /mnt/inst_root

vyos_disk_size: "{{ disk_size | default(10) }}"
vyos_root_fstype: ext4

vyos_target_drive: ""
vyos_raw_img: /tmp/vyos_raw_image.img
grub_console: "kvm"
cloud_init_disable_network_config: false
consistent_network_device_naming: false
